# Name of the workflow
name: Assignment01 Workflow

# Action to trigger the workflow -> In this case, the workflow is triggered when we push something to main branch
on:
  push:
    branches: [ "main" ]

# Define jobs
jobs:
  build:
  
    # Assign runner
    runs-on: ubuntu-latest
    
    # Steps to finish the job
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements.txt && pip install -r requirements-dev.txt
        pip install pytest-xdist
    - name: Test with pytest in general
      run: |
        pytest
    - name: Test with pytest with multiple workers
      run: |
        pytest -n auto
    - name: Print out coverage
      run: |
        py.test --cov .
